version: "3.5"
services:
  api-core:
    image: api-core:v1
    container_name: api-core
    volumes:
      - /app/api-plantform/services/api-core:/jar
    ports:
      - "9001:9001"
    depends_on:
      - api-gateway
  api-interface:
    image: api-interface:v1
    container_name: api-interface
    volumes:
      - /app/api-plantform/services/api-interface:/jar
    ports:
      - "8123:8123"
    depends_on:
      - api-gateway
  api-gateway:
    image: api-gateway:v1
    container_name: api-gateway
    volumes:
      - /app/api-plantform/services/api-gateway:/jar
    ports:
      - "88:88"