spring:
  redis:
    host: 192.168.159.134
    port: 6379
    password: adorabeld4
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        cloud:
          gateway: trace # 设置日志级别