spring:
  redis:
    host: 192.168.159.134
    port: 6379
    password: adorabeld4
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        cloud:
          gateway: trace # 设置日志级别
# knife4j 网关聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    discover:
      # OpenAPI 3.0 规范
      version: openapi3
      enabled: true