# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8123
  servlet:
    # 应用的访问路径
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.dhx.com.api.apiinterface: debug
    org.springframework: warn
# 用户配置
# Spring配置
spring:
  security:
    user:
      password: admin
      name: admin
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  profiles:
    active: druid
  redis:
    # Redis服务器连接端口
#    host: 8.130.79.173
    host: 192.168.159.134
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    password: adorabled4
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
#  rabbitmq:
#    username: dhx
#    password: r324fhh2n3084brj2w
##    host: 8.130.79.173
#    host: 192.168.159.134
#    port: 5672 # 端口
#    virtual-host: / # 虚拟主机
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.134:8848
  application:
    name: api-interface
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.134:3306/api-interface?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

#    password:
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.api.apiinterface.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

weather:
  apiKey: e86fcaac97a97aaa116af494ac1c9bfb

knife4j:
  enable: true
  openapi:
    title: api-plantform_bankend
    description: 接口模块文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://blog.dhx.icu
    terms-of-service-url: https://blog.dhx.icu
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.apiinterface.controller