# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8123
  servlet:
    # 应用的访问路径
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.dhx.com.api.apiinterface: debug
    org.springframework: warn
# 用户配置
# Spring配置
spring:
  security:
    user:
      password: admin
      name: admin
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  profiles:
    active: druid
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.api.apiinterface.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

weather:
  apiKey: e86fcaac97a97aaa116af494ac1c9bfb

knife4j:
  enable: true
  openapi:
    title: api-plantform_bankend
    description: 接口模块文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.apiinterface.controller