# 日志配置
logging:
  level:
    com.dhx.com.api.apiinterface: debug
    org.springframework: warn
dubbo:
  application:
    metadataType: remote
    register-mode: all
    service-discovery:
      migration: FORCE_APPLICATION
    name: api-interface
  protocol:
    name: dubbo
    port: -1
  provider:
    host: ${host.tailscale}
  registry:
    address: nacos://${host.nacos}
    group: ${spring.profiles.active}
    parameters:
      # 这里要在nacos创建名为dubbo的namespace
      namespace: b9970d70-8f1c-402e-b139-4a98f487c197
  # 消费者相关配置
  consumer:
    # 支持校验注解
    validation: true
    # 超时时间
    timeout: 3000
  scan:
    base-packages: com.dhx.apiinterface.service