
# 日志配置
logging:
  level:
    com.dhx.com.api.apiinterface: debug
    org.springframework: warn
spring:
  security:
    user:
      password: admin
      name: admin
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    host: 192.168.159.134
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    password: adorabled4
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.134:8848
  application:
    name: api-interface
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.134:3306/api-interface?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

weather:
  apiKey: e86fcaac97a97aaa116af494ac1c9bfb

knife4j:
  enable: true
  openapi:
    title: api-platform_bankend
    description: 接口模块文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://blog.dhx.icu
    terms-of-service-url: https://blog.dhx.icu
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.apiinterface.controller