# 日志配置
logging:
  level:
    com.dhx.com.api.apiinterface: debug
    org.springframework: warn
spring:
  security:
    user:
      password: admin
      name: admin
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    host: 192.168.159.134
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    password: adorabled4
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.134:3306/api-interface?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

knife4j:
  enable: true
  openapi:
    title: api-platform_bankend
    description: 接口模块文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://blog.dhx.icu
    terms-of-service-url: https://blog.dhx.icu
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.apiinterface.controller

dubbo:
  application:
    metadataType: remote
    register-mode: all
    service-discovery:
      migration: FORCE_APPLICATION
    name: api-interface
  protocol:
    name: dubbo
    port: -1
  provider:
    host: ${host.tailscale}
  registry:
    address: nacos://${host.nacos}
    group: ${spring.profiles.active}
    parameters:
      # 这里要在nacos创建名为dubbo的namespace
      namespace: b9970d70-8f1c-402e-b139-4a98f487c197
  # 消费者相关配置
  consumer:
    # 支持校验注解
    validation: true
    # 超时时间
    timeout: 3000
  scan:
    base-packages: com.dhx.apiinterface.service