spring:
  application:
    name: api-core
  datasource:
    url: jdbc:mysql://192.168.159.134:3306/ry
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器连接端口
    host: 192.168.159.134
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
#    password:

server:
  port: 9001
  servlet:
    context-path: /apicore
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 1 # mybatis-plus 逻辑删除
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql
knife4j:
  enable: true
  openapi:
    title: api-plantform_bankend
    description: 后端接口文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      dev:
        group-name: 开发环境
        api-rule: package
        api-rule-resources:
          - com.dhx.apicore.controller

api:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

dubbo:
  application:
    name: api-core-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://192.168.159.134:8848
dhx:
  client:
    access-key: r3242rfj3w9r
    secret-key: g45hg34wrxsa