spring:
  datasource:
    url: jdbc:mysql://8.130.79.173:4234/api-core
    username: root
    password: 324rfwefefg3f
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器连接端口
    host: 8.130.79.173
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    password: r324fhh2n3084brj2w
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

dubbo:
  application:
    name: api-core-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://8.130.79.173:8848